=== gadget-inc/shopify-webhook-schemas/schemas/2024-04/fulfillments/update.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "properties": {
    "id": {
      "type": "integer"
    },
    "order_id": {
      "type": "integer"
    },
    "status": {
      "type": "string"
    },
    "created_at": {
      "type": "string",
      "format": "date-time"
    },
    "service": {
      "type": [
        "string",
        "null"
      ]
    },
    "updated_at": {
      "type": "string",
      "format": "date-time"
    },
    "tracking_company": {
      "type": "string"
    },
    "shipment_status": {
      "type": [
        "string",
        "null"
      ]
    },
    "location_id": {
      "type": [
        "integer",
        "null"
      ]
    },
    "origin_address": {
      "type": [
        "object",
        "null"
      ],
      "properties": {
        "address1": {
          "type": "string"
        },
        "city": {
          "type": "string"
        },
        "zip": {
          "type": "string"
        },
        "address2": {
          "type": [
            "string",
            "null"
          ]
        },
        "country_code": {
          "type": "string"
        },
        "province_code": {
          "type": "string"
        },
        "first_name": {
          "type": "string"
        },
        "phone": {
          "type": "string"
        },
        "province": {
          "type": "string"
        },
        "country": {
          "type": "string"
        },
        "last_name": {
          "type": "string"
        },
        "company": {
          "type": "string"
        },
        "latitude": {
          "type": "null"
        },
        "longitude": {
          "type": "null"
        },
        "name": {
          "type": "string"
        }
      },
      "required": [
        "address1",
        "city",
        "zip",
        "address2",
        "country_code",
        "province_code"
      ]
    },
    "email": {
      "type": "string",
      "format": "email"
    },
    "destination": {
      "type": "object",
      "properties": {
        "first_name": {
          "type": "string"
        },
        "address1": {
          "type": "string"
        },
        "phone": {
          "type": "string"
        },
        "city": {
          "type": "string"
        },
        "zip": {
          "type": "string"
        },
        "province": {
          "type": "string"
        },
        "country": {
          "type": "string"
        },
        "last_name": {
          "type": "string"
        },
        "address2": {
          "type": "null"
        },
        "company": {
          "type": [
            "string",
            "null"
          ]
        },
        "latitude": {
          "type": [
            "number",
            "null"
          ]
        },
        "longitude": {
          "type": [
            "number",
            "null"
          ]
        },
        "name": {
          "type": "string"
        },
        "country_code": {
          "type": "string"
        },
        "province_code": {
          "type": "string"
        }
      },
      "required": [
        "first_name",
        "address1",
        "phone",
        "city",
        "zip",
        "province",
        "country",
        "last_name",
        "address2",
        "company",
        "latitude",
        "longitude",
        "name",
        "country_code",
        "province_code"
      ]
    },
    "line_items": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer"
          },
          "variant_id": {
            "type": "integer"
          },
          "title": {
            "type": "string"
          },
          "quantity": {
            "type": "integer"
          },
          "sku": {
            "type": "string"
          },
          "variant_title": {
            "type": [
              "string",
              "null"
            ]
          },
          "vendor": {
            "type": [
              "string",
              "null"
            ]
          },
          "fulfillment_service": {
            "type": "string"
          },
          "product_id": {
            "type": "integer"
          },
          "requires_shipping": {
            "type": "boolean"
          },
          "taxable": {
            "type": "boolean"
          },
          "gift_card": {
            "type": "boolean"
          },
          "name": {
            "type": "string"
          },
          "variant_inventory_management": {
            "type": "string"
          },
          "properties": {
            "type": "array",
            "items": false
          },
          "product_exists": {
            "type": "boolean"
          },
          "fulfillable_quantity": {
            "type": "integer"
          },
          "grams": {
            "type": "integer"
          },
          "price": {
            "type": "string"
          },
          "total_discount": {
            "type": "string"
          },
          "fulfillment_status": {
            "type": [
              "string",
              "null"
            ]
          },
          "price_set": {
            "type": "object",
            "properties": {
              "shop_money": {
                "type": "object",
                "properties": {
                  "amount": {
                    "type": "string"
                  },
                  "currency_code": {
                    "type": "string"
                  }
                },
                "required": [
                  "amount",
                  "currency_code"
                ]
              },
              "presentment_money": {
                "type": "object",
                "properties": {
                  "amount": {
                    "type": "string"
                  },
                  "currency_code": {
                    "type": "string"
                  }
                },
                "required": [
                  "amount",
                  "currency_code"
                ]
              }
            },
            "required": [
              "shop_money",
              "presentment_money"
            ]
          },
          "total_discount_set": {
            "type": "object",
            "properties": {
              "shop_money": {
                "type": "object",
                "properties": {
                  "amount": {
                    "type": "string"
                  },
                  "currency_code": {
                    "type": "string"
                  }
                },
                "required": [
                  "amount",
                  "currency_code"
                ]
              },
              "presentment_money": {
                "type": "object",
                "properties": {
                  "amount": {
                    "type": "string"
                  },
                  "currency_code": {
                    "type": "string"
                  }
                },
                "required": [
                  "amount",
                  "currency_code"
                ]
              }
            },
            "required": [
              "shop_money",
              "presentment_money"
            ]
          },
          "discount_allocations": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "amount": {
                  "type": "string"
                },
                "discount_application_index": {
                  "type": "integer"
                },
                "amount_set": {
                  "type": "object",
                  "properties": {
                    "shop_money": {
                      "type": "object",
                      "properties": {
                        "amount": {
                          "type": "string"
                        },
                        "currency_code": {
                          "type": "string"
                        }
                      },
                      "required": [
                        "amount",
                        "currency_code"
                      ]
                    },
                    "presentment_money": {
                      "type": "object",
                      "properties": {
                        "amount": {
                          "type": "string"
                        },
                        "currency_code": {
                          "type": "string"
                        }
                      },
                      "required": [
                        "amount",
                        "currency_code"
                      ]
                    }
                  },
                  "required": [
                    "shop_money",
                    "presentment_money"
                  ]
                }
              },
              "required": [
                "amount",
                "discount_application_index",
                "amount_set"
              ]
            }
          },
          "duties": {
            "type": "array",
            "items": false
          },
          "admin_graphql_api_id": {
            "type": "string",
            "format": "uri"
          },
          "tax_lines": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "rate": {
                  "type": "number"
                },
                "title": {
                  "type": "string"
                },
                "channel_liable": {
                  "type": "boolean"
                },
                "price": {
                  "type": "string"
                },
                "price_set": {
                  "type": "object",
                  "properties": {
                    "presentment_money": {
                      "type": "object",
                      "properties": {
                        "amount": {
                          "type": "string"
                        },
                        "currency_code": {
                          "type": "string"
                        }
                      },
                      "required": [
                        "amount",
                        "currency_code"
                      ]
                    },
                    "shop_money": {
                      "type": "object",
                      "properties": {
                        "amount": {
                          "type": "string"
                        },
                        "currency_code": {
                          "type": "string"
                        }
                      },
                      "required": [
                        "amount",
                        "currency_code"
                      ]
                    }
                  },
                  "required": [
                    "presentment_money",
                    "shop_money"
                  ]
                }
              },
              "required": [
                "rate",
                "title",
                "channel_liable",
                "price",
                "price_set"
              ]
            }
          },
          "tax_code": {
            "type": "string"
          },
          "pre_tax_price_set": {
            "type": "object",
            "properties": {
              "presentment_money": {
                "type": "object",
                "properties": {
                  "amount": {
                    "type": "string"
                  },
                  "currency_code": {
                    "type": "string"
                  }
                },
                "required": [
                  "amount",
                  "currency_code"
                ]
              },
              "shop_money": {
                "type": "object",
                "properties": {
                  "currency_code": {
                    "type": "string"
                  },
                  "amount": {
                    "type": "string"
                  }
                },
                "required": [
                  "currency_code",
                  "amount"
                ]
              }
            },
            "required": [
              "presentment_money",
              "shop_money"
            ]
          },
          "pre_tax_price": {
            "type": "string"
          }
        },
        "required": [
          "id",
          "variant_id",
          "title",
          "quantity",
          "sku",
          "variant_title",
          "vendor",
          "fulfillment_service",
          "product_id",
          "requires_shipping",
          "taxable",
          "gift_card",
          "name",
          "variant_inventory_management",
          "properties",
          "product_exists",
          "fulfillable_quantity",
          "grams",
          "price",
          "total_discount",
          "fulfillment_status",
          "price_set",
          "total_discount_set",
          "discount_allocations",
          "duties",
          "admin_graphql_api_id",
          "tax_lines"
        ]
      }
    },
    "tracking_number": {
      "type": "string"
    },
    "tracking_numbers": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "tracking_url": {
      "type": "string",
      "format": "uri"
    },
    "tracking_urls": {
      "type": "array",
      "items": {
        "type": "string",
        "format": "uri"
      }
    },
    "receipt": {
      "type": "object"
    },
    "name": {
      "type": "string"
    },
    "admin_graphql_api_id": {
      "type": "string",
      "format": "uri"
    }
  },
  "required": [
    "id",
    "order_id",
    "status",
    "created_at",
    "service",
    "updated_at",
    "tracking_company",
    "shipment_status",
    "location_id",
    "origin_address",
    "email",
    "destination",
    "line_items",
    "tracking_number",
    "tracking_numbers",
    "tracking_url",
    "tracking_urls",
    "receipt",
    "name",
    "admin_graphql_api_id"
  ]
}

=== gadget-inc/shopify-webhook-schemas/exemplars/2024-01/fulfillments/1.json
{
  "updated_at": "2019-01-01 00:00:00.000Z",
  "id": 123,
  "destination": {
    "first_name": "example string",
    "phone": "example string",
    "longitude": 123.456,
    "province_code": "example string",
    "province": "example string",
    "latitude": 123.456,
    "address1": "example string",
    "zip": "example string",
    "city": "example string",
    "name": "example string",
    "company": null,
    "last_name": "example string",
    "address2": null,
    "country": "example string",
    "country_code": "example string"
  },
  "created_at": "2019-01-01 00:00:00.000Z",
  "name": "example string",
  "order_id": 123,
  "tracking_url": "https://www.example.com/",
  "origin_address": null,
  "service": "example string",
  "shipment_status": null,
  "tracking_company": "example string",
  "admin_graphql_api_id": "https://www.example.com/",
  "receipt": {},
  "tracking_numbers": [
    "example string"
  ],
  "tracking_urls": [
    "https://www.example.com/"
  ],
  "email": "eallam@example.com",
  "line_items": [
    {
      "duties": [],
      "vendor": "example string",
      "fulfillment_status": "example string",
      "gift_card": false,
      "tax_code": "example string",
      "id": 123,
      "sku": "example string",
      "fulfillable_quantity": 123,
      "name": "example string",
      "product_id": 123,
      "requires_shipping": true,
      "total_discount_set": {
        "presentment_money": {
          "amount": "example string",
          "currency_code": "example string"
        },
        "shop_money": {
          "amount": "example string",
          "currency_code": "example string"
        }
      },
      "variant_inventory_management": "example string",
      "grams": 123,
      "tax_lines": [
        {
          "rate": 123.456,
          "title": "example string",
          "channel_liable": false,
          "price": "example string",
          "price_set": {
            "presentment_money": {
              "amount": "example string",
              "currency_code": "example string"
            },
            "shop_money": {
              "amount": "example string",
              "currency_code": "example string"
            }
          }
        },
        {
          "channel_liable": false,
          "price": "example string",
          "price_set": {
            "presentment_money": {
              "amount": "example string",
              "currency_code": "example string"
            },
            "shop_money": {
              "amount": "example string",
              "currency_code": "example string"
            }
          },
          "rate": 123.456,
          "title": "example string"
        },
        {
          "title": "example string",
          "channel_liable": false,
          "price": "example string",
          "price_set": {
            "presentment_money": {
              "currency_code": "example string",
              "amount": "example string"
            },
            "shop_money": {
              "amount": "example string",
              "currency_code": "example string"
            }
          },
          "rate": 123.456
        },
        {
          "channel_liable": false,
          "price": "example string",
          "price_set": {
            "presentment_money": {
              "amount": "example string",
              "currency_code": "example string"
            },
            "shop_money": {
              "currency_code": "example string",
              "amount": "example string"
            }
          },
          "rate": 123.456,
          "title": "example string"
        },
        {
          "rate": 123.456,
          "title": "example string",
          "channel_liable": false,
          "price": "example string",
          "price_set": {
            "presentment_money": {
              "amount": "example string",
              "currency_code": "example string"
            },
            "shop_money": {
              "amount": "example string",
              "currency_code": "example string"
            }
          }
        }
      ],
      "taxable": true,
      "admin_graphql_api_id": "https://www.example.com/",
      "total_discount": "example string",
      "title": "example string",
      "discount_allocations": [],
      "pre_tax_price_set": {
        "presentment_money": {
          "amount": "example string",
          "currency_code": "example string"
        },
        "shop_money": {
          "currency_code": "example string",
          "amount": "example string"
        }
      },
      "price_set": {
        "presentment_money": {
          "amount": "example string",
          "currency_code": "example string"
        },
        "shop_money": {
          "amount": "example string",
          "currency_code": "example string"
        }
      },
      "product_exists": true,
      "price": "example string",
      "variant_title": "example string",
      "properties": [],
      "fulfillment_service": "example string",
      "quantity": 123,
      "pre_tax_price": "example string",
      "variant_id": 123
    },
    {
      "product_id": 123,
      "properties": [],
      "total_discount": "example string",
      "id": 123,
      "tax_lines": [
        {
          "rate": 123.456,
          "title": "example string",
          "channel_liable": false,
          "price": "example string",
          "price_set": {
            "presentment_money": {
              "currency_code": "example string",
              "amount": "example string"
            },
            "shop_money": {
              "amount": "example string",
              "currency_code": "example string"
            }
          }
        },
        {
          "price_set": {
            "presentment_money": {
              "amount": "example string",
              "currency_code": "example string"
            },
            "shop_money": {
              "amount": "example string",
              "currency_code": "example string"
            }
          },
          "rate": 123.456,
          "title": "example string",
          "channel_liable": false,
          "price": "example string"
        },
        {
          "price": "example string",
          "price_set": {
            "presentment_money": {
              "amount": "example string",
              "currency_code": "example string"
            },
            "shop_money": {
              "amount": "example string",
              "currency_code": "example string"
            }
          },
          "rate": 123.456,
          "title": "example string",
          "channel_liable": false
        },
        {
          "rate": 123.456,
          "title": "example string",
          "channel_liable": false,
          "price": "example string",
          "price_set": {
            "presentment_money": {
              "amount": "example string",
              "currency_code": "example string"
            },
            "shop_money": {
              "amount": "example string",
              "currency_code": "example string"
            }
          }
        },
        {
          "channel_liable": false,
          "price": "example string",
          "price_set": {
            "presentment_money": {
              "amount": "example string",
              "currency_code": "example string"
            },
            "shop_money": {
              "amount": "example string",
              "currency_code": "example string"
            }
          },
          "rate": 123.456,
          "title": "example string"
        }
      ],
      "title": "example string",
      "gift_card": false,
      "fulfillment_service": "example string",
      "name": "example string",
      "quantity": 123,
      "grams": 123,
      "price": "example string",
      "price_set": {
        "presentment_money": {
          "amount": "example string",
          "currency_code": "example string"
        },
        "shop_money": {
          "amount": "example string",
          "currency_code": "example string"
        }
      },
      "pre_tax_price": "example string",
      "fulfillment_status": "example string",
      "product_exists": true,
      "variant_inventory_management": "example string",
      "variant_title": "example string",
      "admin_graphql_api_id": "https://www.example.com/",
      "fulfillable_quantity": 123,
      "pre_tax_price_set": {
        "presentment_money": {
          "amount": "example string",
          "currency_code": "example string"
        },
        "shop_money": {
          "currency_code": "example string",
          "amount": "example string"
        }
      },
      "requires_shipping": true,
      "discount_allocations": [],
      "sku": "example string",
      "total_discount_set": {
        "presentment_money": {
          "amount": "example string",
          "currency_code": "example string"
        },
        "shop_money": {
          "amount": "example string",
          "currency_code": "example string"
        }
      },
      "taxable": true,
      "variant_id": 123,
      "duties": [],
      "tax_code": "example string",
      "vendor": "example string"
    }
  ],
  "status": "example string",
  "location_id": 123,
  "tracking_number": "example string"
}
