=== gadget-inc/shopify-webhook-schemas/schemas/2024-01/products/update.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "properties": {
    "admin_graphql_api_id": {
      "type": "string",
      "format": "uri"
    },
    "body_html": {
      "type": "string"
    },
    "created_at": {
      "type": [
        "string",
        "null"
      ],
      "format": "date-time"
    },
    "handle": {
      "type": "string"
    },
    "id": {
      "type": "integer"
    },
    "product_type": {
      "type": "string"
    },
    "published_at": {
      "type": "string",
      "format": "date-time"
    },
    "template_suffix": {
      "type": [
        "string",
        "null"
      ]
    },
    "title": {
      "type": "string"
    },
    "updated_at": {
      "type": "string",
      "format": "date-time"
    },
    "vendor": {
      "type": "string"
    },
    "status": {
      "type": "string"
    },
    "published_scope": {
      "type": "string"
    },
    "tags": {
      "type": "string"
    },
    "variants": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "admin_graphql_api_id": {
            "type": "string",
            "format": "uri"
          },
          "barcode": {
            "type": [
              "string",
              "null"
            ]
          },
          "compare_at_price": {
            "type": [
              "string",
              "null"
            ]
          },
          "created_at": {
            "type": "string",
            "format": "date-time"
          },
          "fulfillment_service": {
            "type": "string"
          },
          "id": {
            "type": "integer"
          },
          "inventory_management": {
            "type": [
              "string",
              "null"
            ]
          },
          "inventory_policy": {
            "type": "string"
          },
          "position": {
            "type": "integer"
          },
          "price": {
            "type": "string"
          },
          "product_id": {
            "type": "integer"
          },
          "sku": {
            "type": [
              "string",
              "null"
            ]
          },
          "taxable": {
            "type": "boolean"
          },
          "title": {
            "type": "string"
          },
          "updated_at": {
            "type": "string",
            "format": "date-time"
          },
          "option1": {
            "type": "string"
          },
          "option2": {
            "type": [
              "string",
              "null"
            ]
          },
          "option3": {
            "type": [
              "string",
              "null"
            ]
          },
          "grams": {
            "type": "integer"
          },
          "image_id": {
            "type": [
              "integer",
              "null"
            ]
          },
          "weight": {
            "type": "number"
          },
          "weight_unit": {
            "type": "string"
          },
          "inventory_item_id": {
            "type": [
              "integer",
              "null"
            ]
          },
          "inventory_quantity": {
            "type": "integer"
          },
          "old_inventory_quantity": {
            "type": "integer"
          },
          "requires_shipping": {
            "type": "boolean"
          }
        },
        "required": [
          "admin_graphql_api_id",
          "barcode",
          "compare_at_price",
          "created_at",
          "fulfillment_service",
          "id",
          "inventory_management",
          "inventory_policy",
          "position",
          "price",
          "product_id",
          "sku",
          "taxable",
          "title",
          "updated_at",
          "option1",
          "option2",
          "option3",
          "grams",
          "image_id",
          "weight",
          "weight_unit",
          "inventory_item_id",
          "inventory_quantity",
          "old_inventory_quantity",
          "requires_shipping"
        ]
      }
    },
    "options": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer"
          },
          "name": {
            "type": "string"
          },
          "position": {
            "type": "integer"
          },
          "product_id": {
            "type": "integer"
          },
          "values": {
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        },
        "required": [
          "id",
          "name",
          "position",
          "product_id",
          "values"
        ]
      }
    },
    "images": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "height": {
            "type": "integer"
          },
          "id": {
            "type": "integer"
          },
          "src": {
            "type": "string",
            "format": "uri"
          },
          "updated_at": {
            "type": "string",
            "format": "date-time"
          },
          "variant_ids": {
            "type": "array",
            "items": {
              "type": "integer"
            }
          },
          "admin_graphql_api_id": {
            "type": "string",
            "format": "uri"
          },
          "alt": {
            "type": "null"
          },
          "created_at": {
            "type": "string",
            "format": "date-time"
          },
          "product_id": {
            "type": "integer"
          },
          "position": {
            "type": "integer"
          },
          "width": {
            "type": "integer"
          }
        },
        "required": [
          "height",
          "id",
          "src",
          "updated_at",
          "variant_ids",
          "admin_graphql_api_id",
          "alt",
          "created_at",
          "product_id",
          "position",
          "width"
        ]
      }
    },
    "image": {
      "anyOf": [
        {
          "type": "string",
          "format": "uri"
        },
        {
          "type": "object",
          "properties": {
            "height": {
              "type": "integer"
            },
            "position": {
              "type": "integer"
            },
            "updated_at": {
              "type": "string",
              "format": "date-time"
            },
            "variant_ids": {
              "type": "array",
              "items": {
                "type": "integer"
              }
            },
            "admin_graphql_api_id": {
              "type": "string",
              "format": "uri"
            },
            "created_at": {
              "type": "string",
              "format": "date-time"
            },
            "product_id": {
              "type": "integer"
            },
            "alt": {
              "type": "null"
            },
            "src": {
              "type": "string",
              "format": "uri"
            },
            "width": {
              "type": "integer"
            },
            "id": {
              "type": "integer"
            }
          },
          "required": [
            "height",
            "position",
            "updated_at",
            "variant_ids",
            "admin_graphql_api_id",
            "created_at",
            "product_id",
            "alt",
            "src",
            "width",
            "id"
          ]
        }
      ]
    },
    "variant_ids": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer"
          }
        },
        "required": [
          "id"
        ]
      }
    }
  },
  "required": [
    "admin_graphql_api_id",
    "body_html",
    "created_at",
    "handle",
    "id",
    "product_type",
    "published_at",
    "template_suffix",
    "title",
    "updated_at",
    "vendor",
    "status",
    "published_scope",
    "tags",
    "variants",
    "options",
    "images",
    "image",
    "variant_ids"
  ]
}

=== gadget-inc/shopify-webhook-schemas/exemplars/2023-10/products/3.json
{
  "published_scope": "example string",
  "options": [
    {
      "values": [
        "example string",
        "example string",
        "example string"
      ],
      "id": 123,
      "name": "example string",
      "position": 123,
      "product_id": 123
    },
    {
      "position": 123,
      "product_id": 123,
      "values": [
        "example string"
      ],
      "id": 123,
      "name": "example string"
    }
  ],
  "vendor": "example string",
  "published_at": "2019-01-01 00:00:00.000Z",
  "body_html": "example string",
  "id": 123,
  "image": {
    "height": 123,
    "position": 123,
    "updated_at": "2019-01-01 00:00:00.000Z",
    "variant_ids": [
      123,
      123,
      123
    ],
    "admin_graphql_api_id": "https://www.example.com/",
    "created_at": "2019-01-01 00:00:00.000Z",
    "product_id": 123,
    "alt": null,
    "src": "https://www.example.com/",
    "width": 123,
    "id": 123
  },
  "template_suffix": null,
  "admin_graphql_api_id": "https://www.example.com/",
  "variants": [
    {
      "barcode": null,
      "option1": "example string",
      "product_id": 123,
      "sku": "example string",
      "weight_unit": "example string",
      "option3": null,
      "old_inventory_quantity": 123,
      "option2": "example string",
      "inventory_policy": "example string",
      "grams": 123,
      "inventory_item_id": 123,
      "position": 123,
      "weight": 123.456,
      "id": 123,
      "title": "example string",
      "image_id": 123,
      "inventory_quantity": 123,
      "updated_at": "2019-01-01 00:00:00.000Z",
      "admin_graphql_api_id": "https://www.example.com/",
      "compare_at_price": null,
      "taxable": true,
      "price": "example string",
      "created_at": "2019-01-01 00:00:00.000Z",
      "requires_shipping": true,
      "inventory_management": "example string",
      "fulfillment_service": "example string"
    },
    {
      "inventory_management": "example string",
      "position": 123,
      "option1": "example string",
      "image_id": 123,
      "inventory_quantity": 123,
      "old_inventory_quantity": 123,
      "fulfillment_service": "example string",
      "barcode": null,
      "compare_at_price": null,
      "created_at": "2019-01-01 00:00:00.000Z",
      "grams": 123,
      "weight_unit": "example string",
      "sku": "example string",
      "weight": 123.456,
      "option2": "example string",
      "product_id": 123,
      "inventory_policy": "example string",
      "taxable": true,
      "requires_shipping": true,
      "updated_at": "2019-01-01 00:00:00.000Z",
      "inventory_item_id": 123,
      "admin_graphql_api_id": "https://www.example.com/",
      "id": 123,
      "option3": null,
      "price": "example string",
      "title": "example string"
    },
    {
      "created_at": "2019-01-01 00:00:00.000Z",
      "barcode": null,
      "updated_at": "2019-01-01 00:00:00.000Z",
      "inventory_management": "example string",
      "option1": "example string",
      "sku": "example string",
      "option2": "example string",
      "price": "example string",
      "grams": 123,
      "inventory_policy": "example string",
      "admin_graphql_api_id": "https://www.example.com/",
      "weight": 123.456,
      "position": 123,
      "id": 123,
      "fulfillment_service": "example string",
      "taxable": true,
      "old_inventory_quantity": 123,
      "title": "example string",
      "product_id": 123,
      "requires_shipping": true,
      "weight_unit": "example string",
      "inventory_quantity": 123,
      "option3": null,
      "image_id": 123,
      "compare_at_price": null,
      "inventory_item_id": 123
    }
  ],
  "updated_at": "2019-01-01 00:00:00.000Z",
  "images": [
    {
      "height": 123,
      "id": 123,
      "src": "https://www.example.com/",
      "updated_at": "2019-01-01 00:00:00.000Z",
      "variant_ids": [
        123,
        123,
        123
      ],
      "admin_graphql_api_id": "https://www.example.com/",
      "alt": null,
      "created_at": "2019-01-01 00:00:00.000Z",
      "product_id": 123,
      "position": 123,
      "width": 123
    },
    {
      "width": 123,
      "height": 123,
      "id": 123,
      "position": 123,
      "src": "https://www.example.com/",
      "variant_ids": [],
      "alt": null,
      "created_at": "2019-01-01 00:00:00.000Z",
      "admin_graphql_api_id": "https://www.example.com/",
      "updated_at": "2019-01-01 00:00:00.000Z",
      "product_id": 123
    },
    {
      "updated_at": "2019-01-01 00:00:00.000Z",
      "variant_ids": [],
      "height": 123,
      "id": 123,
      "src": "https://www.example.com/",
      "admin_graphql_api_id": "https://www.example.com/",
      "created_at": "2019-01-01 00:00:00.000Z",
      "position": 123,
      "product_id": 123,
      "alt": null,
      "width": 123
    },
    {
      "created_at": "2019-01-01 00:00:00.000Z",
      "id": 123,
      "product_id": 123,
      "updated_at": "2019-01-01 00:00:00.000Z",
      "width": 123,
      "admin_graphql_api_id": "https://www.example.com/",
      "alt": null,
      "src": "https://www.example.com/",
      "height": 123,
      "position": 123,
      "variant_ids": []
    },
    {
      "src": "https://www.example.com/",
      "variant_ids": [],
      "width": 123,
      "admin_graphql_api_id": "https://www.example.com/",
      "updated_at": "2019-01-01 00:00:00.000Z",
      "id": 123,
      "created_at": "2019-01-01 00:00:00.000Z",
      "alt": null,
      "position": 123,
      "height": 123,
      "product_id": 123
    }
  ],
  "tags": "example string",
  "status": "example string",
  "product_type": "example string",
  "title": "example string",
  "handle": "example string",
  "variant_ids": [
    {
      "id": 123
    },
    {
      "id": 123
    },
    {
      "id": 123
    }
  ],
  "created_at": "2019-01-01 00:00:00.000Z"
}
