=== gadget-inc/shopify-webhook-schemas/schemas/2024-07/disputes/update.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "properties": {
    "amount": {
      "type": "string"
    },
    "currency": {
      "type": "string"
    },
    "evidence_due_by": {
      "format": "date-time",
      "type": "string"
    },
    "evidence_sent_on": {
      "format": "date-time",
      "type": [
        "null",
        "string"
      ]
    },
    "finalized_on": {
      "format": "date-time",
      "type": [
        "null",
        "string"
      ]
    },
    "id": {
      "type": "integer"
    },
    "initiated_at": {
      "format": "date-time",
      "type": "string"
    },
    "network_reason_code": {
      "type": "string"
    },
    "order_id": {
      "type": "integer"
    },
    "reason": {
      "type": "string"
    },
    "status": {
      "type": "string"
    },
    "type": {
      "type": "string"
    }
  },
  "required": [
    "amount",
    "currency",
    "evidence_due_by",
    "evidence_sent_on",
    "finalized_on",
    "id",
    "initiated_at",
    "network_reason_code",
    "order_id",
    "reason",
    "status",
    "type"
  ],
  "type": "object"
}

=== gadget-inc/shopify-webhook-schemas/exemplars/2025-04/disputes/1.json
{
  "id": 123,
  "order_id": 123,
  "type": "example string",
  "amount": "example string",
  "currency": "example string",
  "reason": "example string",
  "network_reason_code": "example string",
  "status": "example string",
  "evidence_due_by": "2019-01-01 00:00:00.000Z",
  "evidence_sent_on": "2019-01-01 00:00:00.000Z",
  "finalized_on": "2019-01-01 00:00:00.000Z",
  "initiated_at": "2019-01-01 00:00:00.000Z"
}
