=== gadget-inc/shopify-webhook-schemas/schemas/2025-07/collections/create.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "properties": {
    "admin_graphql_api_id": {
      "format": "uri",
      "type": "string"
    },
    "body_html": {
      "type": "string"
    },
    "handle": {
      "type": "string"
    },
    "id": {
      "type": "integer"
    },
    "image": {
      "properties": {
        "alt": {
          "type": "string"
        },
        "created_at": {
          "type": "string"
        },
        "height": {
          "type": "number"
        },
        "src": {
          "type": "string"
        },
        "width": {
          "type": "number"
        }
      },
      "type": "object"
    },
    "published_at": {
      "format": "date-time",
      "type": "string"
    },
    "published_scope": {
      "type": "string"
    },
    "sort_order": {
      "type": [
        "null",
        "string"
      ]
    },
    "template_suffix": {
      "type": [
        "null",
        "string"
      ]
    },
    "title": {
      "type": "string"
    },
    "updated_at": {
      "format": "date-time",
      "type": "string"
    }
  },
  "required": [
    "admin_graphql_api_id",
    "body_html",
    "handle",
    "id",
    "published_at",
    "published_scope",
    "sort_order",
    "template_suffix",
    "title",
    "updated_at"
  ],
  "type": "object"
}

=== gadget-inc/shopify-webhook-schemas/exemplars/2025-04/collections/1.json
{
  "admin_graphql_api_id": "https://www.example.com/",
  "body_html": "example string",
  "handle": "example string",
  "id": 123,
  "image": {
    "alt": "example string",
    "created_at": "2019-01-01 00:00:00.000Z",
    "height": 123,
    "src": "https://www.example.com/",
    "width": 123
  },
  "published_at": "2019-01-01 00:00:00.000Z",
  "published_scope": "example string",
  "sort_order": "example string",
  "template_suffix": "example string",
  "title": "example string",
  "updated_at": "2019-01-01 00:00:00.000Z"
}
