=== gadget-inc/shopify-webhook-schemas/schemas/2024-10/company_contacts/update.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "properties": {
    "customer_admin_graphql_api_id": {
      "type": "string",
      "format": "uri"
    },
    "title": {
      "type": "string"
    },
    "locale": {
      "type": "string"
    },
    "created_at": {
      "type": "string",
      "format": "date-time"
    },
    "updated_at": {
      "type": "string",
      "format": "date-time"
    },
    "admin_graphql_api_id": {
      "type": "string",
      "format": "uri"
    },
    "company": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "note": {
          "type": "string"
        },
        "external_id": {
          "type": "string"
        },
        "main_contact_admin_graphql_api_id": {
          "type": "string",
          "format": "uri"
        },
        "created_at": {
          "type": "string",
          "format": "date-time"
        },
        "updated_at": {
          "type": "string",
          "format": "date-time"
        },
        "customer_since": {
          "type": "string",
          "format": "date-time"
        },
        "admin_graphql_api_id": {
          "type": "string",
          "format": "uri"
        }
      },
      "required": [
        "name",
        "note",
        "external_id",
        "main_contact_admin_graphql_api_id",
        "created_at",
        "updated_at",
        "customer_since",
        "admin_graphql_api_id"
      ]
    }
  },
  "required": [
    "customer_admin_graphql_api_id",
    "title",
    "locale",
    "created_at",
    "updated_at",
    "admin_graphql_api_id",
    "company"
  ]
}

=== gadget-inc/shopify-webhook-schemas/exemplars/2025-07/company_contacts/1.json
{
  "admin_graphql_api_id": "https://www.example.com/",
  "company": {
    "admin_graphql_api_id": "https://www.example.com/",
    "created_at": "2019-01-01 00:00:00.000Z",
    "customer_since": "2019-01-01 00:00:00.000Z",
    "external_id": "example string",
    "main_contact_admin_graphql_api_id": "https://www.example.com/",
    "name": "example string",
    "note": "example string",
    "updated_at": "2019-01-01 00:00:00.000Z"
  },
  "created_at": "2019-01-01 00:00:00.000Z",
  "customer_admin_graphql_api_id": "https://www.example.com/",
  "locale": "example string",
  "title": "example string",
  "updated_at": "2019-01-01 00:00:00.000Z"
}
