=== gadget-inc/shopify-webhook-schemas/schemas/2026-04/carts/create.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "properties": {
    "created_at": {
      "format": "date-time",
      "type": "string"
    },
    "id": {
      "type": "string"
    },
    "line_items": {
      "items": {
        "properties": {
          "discounted_price": {
            "type": "string"
          },
          "discounted_price_set": {
            "properties": {
              "presentment_money": {
                "properties": {
                  "amount": {
                    "type": "string"
                  },
                  "currency_code": {
                    "type": "string"
                  }
                },
                "required": [
                  "amount",
                  "currency_code"
                ],
                "type": "object"
              },
              "shop_money": {
                "properties": {
                  "amount": {
                    "type": "string"
                  },
                  "currency_code": {
                    "type": "string"
                  }
                },
                "required": [
                  "amount",
                  "currency_code"
                ],
                "type": "object"
              }
            },
            "required": [
              "presentment_money",
              "shop_money"
            ],
            "type": "object"
          },
          "discounts": {
            "items": false,
            "type": "array"
          },
          "gift_card": {
            "type": "boolean"
          },
          "grams": {
            "type": "integer"
          },
          "id": {
            "type": "integer"
          },
          "key": {
            "type": "string"
          },
          "line_price": {
            "type": "string"
          },
          "line_price_set": {
            "properties": {
              "presentment_money": {
                "properties": {
                  "amount": {
                    "type": "string"
                  },
                  "currency_code": {
                    "type": "string"
                  }
                },
                "required": [
                  "amount",
                  "currency_code"
                ],
                "type": "object"
              },
              "shop_money": {
                "properties": {
                  "amount": {
                    "type": "string"
                  },
                  "currency_code": {
                    "type": "string"
                  }
                },
                "required": [
                  "amount",
                  "currency_code"
                ],
                "type": "object"
              }
            },
            "required": [
              "presentment_money",
              "shop_money"
            ],
            "type": "object"
          },
          "original_line_price": {
            "type": "string"
          },
          "original_line_price_set": {
            "properties": {
              "presentment_money": {
                "properties": {
                  "amount": {
                    "type": "string"
                  },
                  "currency_code": {
                    "type": "string"
                  }
                },
                "required": [
                  "amount",
                  "currency_code"
                ],
                "type": "object"
              },
              "shop_money": {
                "properties": {
                  "amount": {
                    "type": "string"
                  },
                  "currency_code": {
                    "type": "string"
                  }
                },
                "required": [
                  "amount",
                  "currency_code"
                ],
                "type": "object"
              }
            },
            "required": [
              "presentment_money",
              "shop_money"
            ],
            "type": "object"
          },
          "original_price": {
            "type": "string"
          },
          "parent_relationship": {
            "type": "null"
          },
          "price": {
            "type": "string"
          },
          "price_set": {
            "properties": {
              "presentment_money": {
                "properties": {
                  "amount": {
                    "type": "string"
                  },
                  "currency_code": {
                    "type": "string"
                  }
                },
                "required": [
                  "amount",
                  "currency_code"
                ],
                "type": "object"
              },
              "shop_money": {
                "properties": {
                  "amount": {
                    "type": "string"
                  },
                  "currency_code": {
                    "type": "string"
                  }
                },
                "required": [
                  "amount",
                  "currency_code"
                ],
                "type": "object"
              }
            },
            "required": [
              "presentment_money",
              "shop_money"
            ],
            "type": "object"
          },
          "product_id": {
            "type": "integer"
          },
          "properties": {
            "type": "null"
          },
          "quantity": {
            "type": "integer"
          },
          "sku": {
            "type": "string"
          },
          "taxable": {
            "type": "boolean"
          },
          "title": {
            "type": "string"
          },
          "total_discount": {
            "type": "string"
          },
          "total_discount_set": {
            "properties": {
              "presentment_money": {
                "properties": {
                  "amount": {
                    "type": "string"
                  },
                  "currency_code": {
                    "type": "string"
                  }
                },
                "required": [
                  "amount",
                  "currency_code"
                ],
                "type": "object"
              },
              "shop_money": {
                "properties": {
                  "amount": {
                    "type": "string"
                  },
                  "currency_code": {
                    "type": "string"
                  }
                },
                "required": [
                  "amount",
                  "currency_code"
                ],
                "type": "object"
              }
            },
            "required": [
              "presentment_money",
              "shop_money"
            ],
            "type": "object"
          },
          "variant_id": {
            "type": "integer"
          },
          "vendor": {
            "type": "string"
          }
        },
        "required": [
          "discounted_price",
          "discounted_price_set",
          "discounts",
          "gift_card",
          "grams",
          "id",
          "key",
          "line_price",
          "line_price_set",
          "original_line_price",
          "original_line_price_set",
          "original_price",
          "price",
          "price_set",
          "product_id",
          "properties",
          "quantity",
          "sku",
          "taxable",
          "title",
          "total_discount",
          "total_discount_set",
          "variant_id",
          "vendor"
        ],
        "type": "object"
      },
      "type": "array"
    },
    "note": {
      "type": [
        "null",
        "string"
      ]
    },
    "token": {
      "type": "string"
    },
    "updated_at": {
      "format": "date-time",
      "type": "string"
    }
  },
  "required": [
    "created_at",
    "id",
    "line_items",
    "note",
    "token",
    "updated_at"
  ],
  "type": "object"
}

=== gadget-inc/shopify-webhook-schemas/exemplars/2025-07/carts/1.json
{
  "created_at": "2019-01-01 00:00:00.000Z",
  "id": "example string",
  "line_items": [
    {
      "discounted_price": "example string",
      "discounted_price_set": {
        "presentment_money": {
          "amount": "example string",
          "currency_code": "example string"
        },
        "shop_money": {
          "amount": "example string",
          "currency_code": "example string"
        }
      },
      "discounts": [],
      "gift_card": false,
      "grams": 123,
      "id": 123,
      "key": "example string",
      "line_price": "example string",
      "line_price_set": {
        "presentment_money": {
          "amount": "example string",
          "currency_code": "example string"
        },
        "shop_money": {
          "amount": "example string",
          "currency_code": "example string"
        }
      },
      "original_line_price": "example string",
      "original_line_price_set": {
        "presentment_money": {
          "amount": "example string",
          "currency_code": "example string"
        },
        "shop_money": {
          "amount": "example string",
          "currency_code": "example string"
        }
      },
      "original_price": "example string",
      "price": "example string",
      "price_set": {
        "presentment_money": {
          "amount": "example string",
          "currency_code": "example string"
        },
        "shop_money": {
          "amount": "example string",
          "currency_code": "example string"
        }
      },
      "product_id": 123,
      "properties": null,
      "quantity": 123,
      "sku": "example string",
      "taxable": true,
      "title": "example string",
      "total_discount": "example string",
      "total_discount_set": {
        "presentment_money": {
          "amount": "example string",
          "currency_code": "example string"
        },
        "shop_money": {
          "amount": "example string",
          "currency_code": "example string"
        }
      },
      "variant_id": 123,
      "vendor": "example string"
    },
    {
      "discounted_price": "example string",
      "discounted_price_set": {
        "presentment_money": {
          "amount": "example string",
          "currency_code": "example string"
        },
        "shop_money": {
          "amount": "example string",
          "currency_code": "example string"
        }
      },
      "discounts": [],
      "gift_card": false,
      "grams": 123,
      "id": 123,
      "key": "example string",
      "line_price": "example string",
      "line_price_set": {
        "presentment_money": {
          "amount": "example string",
          "currency_code": "example string"
        },
        "shop_money": {
          "amount": "example string",
          "currency_code": "example string"
        }
      },
      "original_line_price": "example string",
      "original_line_price_set": {
        "presentment_money": {
          "amount": "example string",
          "currency_code": "example string"
        },
        "shop_money": {
          "amount": "example string",
          "currency_code": "example string"
        }
      },
      "original_price": "example string",
      "price": "example string",
      "price_set": {
        "presentment_money": {
          "amount": "example string",
          "currency_code": "example string"
        },
        "shop_money": {
          "amount": "example string",
          "currency_code": "example string"
        }
      },
      "product_id": 123,
      "properties": null,
      "quantity": 123,
      "sku": "example string",
      "taxable": true,
      "title": "example string",
      "total_discount": "example string",
      "total_discount_set": {
        "presentment_money": {
          "amount": "example string",
          "currency_code": "example string"
        },
        "shop_money": {
          "amount": "example string",
          "currency_code": "example string"
        }
      },
      "variant_id": 123,
      "vendor": "example string"
    }
  ],
  "note": "example string",
  "token": "example string",
  "updated_at": "2019-01-01 00:00:00.000Z"
}
